"""add_capacity_to_events_and_create_users_table

Revision ID: f2298640cae0
Revises:
Create Date: 2025-11-07 11:44:20.462394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2298640cae0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # Add capacity column with default value for existing rows
    op.add_column("events", sa.Column("capacity", sa.Integer(), nullable=True))
    op.execute("UPDATE events SET capacity = 100 WHERE capacity IS NULL")
    op.alter_column("events", "capacity", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "capacity")
    op.drop_table("users")
    # ### end Alembic commands ###
